repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        language_version: python3.8
        args: ['--target-version', 'py38']
  - repo: https://github.com/pycqa/isort
    # isort config is in setup.cfg
    rev: 5.10.1
    hooks:
      - id: isort
        language_version: python3
  - repo: https://github.com/pycqa/flake8
    # flake8 config is in setup.cfg
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-assertive
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==22.1.0]
