
version: "3.8"

volumes:
  postgres-data:

services:
  # a postgres container for providing database access.
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      # make available on host so runserver running locally can connect.
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
