[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "wagtail-grapple"
authors = [
    {name = "Nathan Horrigan", email = "hello@torchbox.com"}
]
maintainers = [
    {name = "Dan Braghis", email = "dan.braghis@torchbox.com"}
]
description = "A Wagtail package that speeds up and simplifies implementing a GraphQL endpoint!"
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Framework :: Django",
    "Framework :: Django :: 3.2",
    "Framework :: Django :: 4.0",
    "Framework :: Django :: 4.1",
    "Framework :: Wagtail",
    "Framework :: Wagtail :: 4",
]
dynamic = ["version"]
requires-python = ">=3.8"
dependencies = [
    "wagtail>=4.1",
    "graphene-django>=3,<4",
    "wagtail-headless-preview"
]

[project.optional-dependencies]
channels = [
    "Django>=3.2,<4.0",
    "channels>=3.0,<3.1",
]

[project.urls]
Changelog = "https://github.com/torchbox/wagtail-grapple/blob/main/CHANGELOG.md"

[tool.flit.module]
name = "grapple"

[tool.flit.sdist]
exclude = [
    "docs",
    "tests",
    "CHANGELOG.md",
    "Dockerfile",
    "Makefile",
    ".*",
    "*.json",
    "*.ini",
    "*.yml"
]
include = ["LICENSE"]

[tool.isort]
profile = "black"
skip = [".git",".github",".tox",".venv", "__pycache__","LC_MESSAGES","build","dist","docs","locale","migrations","venv"]
blocked_extensions = ["rst", "md", "html", "svg", "txt", "css", "scss", "png", "sh"]
known_first_party = ["grapple", "testapp"]
default_section = "THIRDPARTY"

[tool.doc8]
ignore = ["D000", "D001"]
ignore_path = ["docs/build", "src", "tests", ".git", ".tox", ".venv"]
