name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allowfail }}
    strategy:
      fail-fast: false
      max-parallel: 4
      allowfail: [false]
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        wagtail-version: ['4.1', '4.2', 'main']
        include:
          - python-version: '3.11'
            wagtail-version: '4.1'
          - python-version: '3.11'
            wagtail-version: '4.2'
          - python-version: '3.11'
            wagtail-version: 'main'
            allowfail: true

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install .

      - name: Install Wagtail package
        if: ${{ matrix.wagtail-version != 'main' }}
        run: |
          pip install wagtail==${{ matrix.wagtail-version }}

      - name: Install Wagtail main
        if: ${{ matrix.wagtail-version == 'main' }}
        run: |
          git clone https://github.com/wagtail/wagtail.git
          pip install ./wagtail

      - name: Run Tests
        run: |
          cd example
          python manage.py migrate
          python manage.py test

  test_channels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: 'pip'
          cache-dependency-path: |
            requirements-channels.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements-channels.txt
          pip install .

      - name: Run Tests
        run: |
          cd example
          python manage.py migrate
          python manage.py test
