name: Ruff

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
    branches: [main]

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # keep in sync with .pre-commit-config.yaml and tests/requirements.txt
    - run: python -Im pip install --user ruff==0.9.4

    - name: Run ruff
      run: ruff --output-format=github grapple
